name: Create and publish a Docker image

on:
  push:
    branches: ['master']

jobs:
  scp-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/"
          REMOTE_HOST: "18.223.247.193"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/github_enigma/"
          EXCLUDE: "/dist/, /node_modules/"
