name: Create and publish a Docker image

on:
  push:
    branches: ['master']

jobs:
  scp-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH Deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rv -i"
        SOURCE: "./"
        REMOTE_HOST: "18.223.247.193"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/github_enigma/"

      
